# Generated by Django 5.1.4 on 2024-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(default='NOT20241218-0001', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
