# Generated by Django 5.1.4 on 2024-12-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notification_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='points_balance',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
